# Form implementation generated from reading ui file 'E:\Licenta\windows\areYouSure.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(470, 314)
        self.NoButton = QtWidgets.QPushButton(parent=Form)
        self.NoButton.setGeometry(QtCore.QRect(270, 210, 75, 23))
        self.NoButton.setObjectName("NoButton")
        self.yesButton = QtWidgets.QPushButton(parent=Form)
        self.yesButton.setGeometry(QtCore.QRect(120, 210, 75, 23))
        self.yesButton.setObjectName("yesButton")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(200, 130, 101, 16))
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.NoButton.setText(_translate("Form", "No"))
        self.yesButton.setText(_translate("Form", "Yes"))
        self.label.setText(_translate("Form", "Are You Sure?"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
